services:
  db:
    image: postgres
    restart: on-failure
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: local
    volumes:
      - postgres-data:/var/lib/postgresql/data

  minio:
    image: bitnami/minio:2024.10.13
    ports:
      - '9000:9000' # API port
      - '9001:9001' # Console port
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY_ID}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_ACCESS_KEY}
      MINIO_DEFAULT_BUCKETS: assets,${S3_INVENTORY_BUCKET_NAME}
    volumes:
      - minio-data:/data

  app:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    command: bash -c "npm i && npm run dev"
    working_dir: /home/node
    environment:
      DATABASE_URL: postgres://root:mysecretpassword@db:5432/local
      S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
      S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
      S3_REGION: ${S3_REGION}
      S3_ENDPOINT: http://minio:9000
      S3_FORCE_PATH_STYLE: ${S3_FORCE_PATH_STYLE}
      S3_INVENTORY_BUCKET_NAME: ${S3_INVENTORY_BUCKET_NAME}
    ports:
      - 5173:5173
      - 9323:9323
    volumes:
      - .:/home/node
    depends_on:
      - db

volumes:
  postgres-data: {}
  minio-data: {}
