services:
  db:
    image: postgres
    restart: on-failure
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: local
    volumes:
      - postgres-data:/var/lib/postgresql/data

  minio:
    image: bitnami/minio:2024.10.13
    ports:
      - '9000:9000' # API port
      - '9001:9001' # Console port
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY_ID}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_ACCESS_KEY}
      MINIO_DEFAULT_BUCKETS: assets,${S3_INVENTORY_BUCKET_NAME}
    volumes:
      - minio-data:/data

volumes:
  postgres-data: {}
  minio-data: {}
