services:
  db:
    image: postgres
    restart: on-failure
    ports:
      - 5432:5432
    environment: 
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: local
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: {}